# The vic3-tiger.conf file is in standard Paradox script format.
# It should be placed in the top directory of your mod.

languages = {
	check = "english"
    check = "simp_chinese"
}

# Allows configuring what reports are printed
filter = {

    # Whether to report about problems in vanilla game files.
    # Setting this to 'yes' results in a LOT of spam.
    # Optional boolean value, defaults to no.
    show_vanilla = no

    # Whether to report about problems in mods loaded via the load_mod sections.
    # Optional boolean value, defaults to no.
    show_loaded_mods = no

    # Contains rules for reports, using trigger syntax.
    # Only reports matching the trigger will be printed.
    # The root trigger is an AND block, just like any other trigger.
    trigger = {
        # For more information, there is a guide at: ck3-tiger/filter.md
        # In short, valid trigger keys are:
        # - always = yes/no
        # - NOT, AND, OR, NAND, NOR
        # - severity
        # - confidence
        # - key
        # - file
        # - text
        # - ignore_keys_in_files
        NOR = {
            
            AND = {
                key  = scopes
                text = "EACP_"
            }
            
        }
    }
}

load_mod = {
    label = "EAC"
    mod   = "C:/Steam/steamapps/workshop/content/529340/2950237509/"
}
load_mod = {
    label = "WCR"
    mod   = "C:/Users/James/Documents/Paradox Interactive/Victoria 3/mod/WCR"
}
